import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Header
    nav_home: "HOME",
    nav_experiences: "EXPERIENCES",
    nav_activities: "ACTIVITIES",
    nav_tours: "TOURS",
    nav_gallery: "GALLERY",
    nav_pricing: "PRICING",
    nav_route: "ROUTE",
    nav_horse_riding: "HORSES",
    nav_about: "ABOUT US",
    nav_contact: "CONTACT",
    book_experience: "BOOK EXPERIENCE",

    // Hero
    hero_badge: "Moroccan Desert & Coastal Adventures",
    hero_title_1: "EXPERIENCE AGADIR",
    hero_title_2: "DIFFERENTLY",
    hero_desc: "Authentic camel rides, ocean sunset adventures, and coastal equestrian trails. Glide through eucalyptus groves and estuary dunes under Morocco's golden hour.",
    hero_chip_1: "Camel Experiences",
    hero_chip_2: "Horse Riding",
    hero_chip_3: "Atlantic Sunset",
    hero_chip_4: "Souss Valley Tours",
    hero_chip_5: "Desert Safaris",
    btn_book: "BOOK YOUR EXPERIENCE",
    btn_explore: "EXPLORE ACTIVITIES",

    // Booking Form
    form_adventure: "Choose Adventure",
    form_date: "Select Date",
    form_travelers: "Travelers",
    btn_check_availability: "Check Availability",
    person_1: "1 Person (Private or Group)",
    person_2: "2 Travelers",
    person_3: "3 Travelers",
    person_4: "4 Travelers",
    person_5: "Family Group (5+)",

    // Why Us
    why_badge: "The Trusted Agadir Difference",
    why_title: "WHY TRAVELERS LOVE AGADIR CAMEL EXPERIENCE",
    why_desc: "Curated desert encounters with genuine Berber warmth, reliable hotel door-to-door transit, and no hidden surprises.",
    pillar_1_title: "Authentic Experiences",
    pillar_1_desc: "True Berber hospitality, traditional handcrafted leather saddles, and scenic uncrowded trails along coastal dunes and the serene Souss River.",
    pillar_1_tag: "Berber Heritage",
    pillar_2_title: "Hotel Pickup Included",
    pillar_2_desc: "Complimentary air-conditioned transfer directly from your Agadir or Taghazout hotel reception, returning you safely right after the ride.",
    pillar_2_tag: "Agadir & Taghazout",
    pillar_3_title: "Friendly Local Team",
    pillar_3_desc: "Experienced, multilingual camel handlers who treat travelers like family, capturing photos and sharing stories of the Souss region.",
    pillar_3_tag: "Local Guides",
    pillar_4_title: "Unforgettable Sunsets",
    pillar_4_desc: "Carefully timed departures that place you beside the Atlantic dunes exactly when the sky blushes amber, rose, and burnished gold.",
    pillar_4_tag: "Golden Hour",

    // Featured Experience
    iconic_badge: "Most Iconic Journey",
    camel_sunset_title: "CAMEL SUNSET EXPERIENCE",
    camel_sunset_desc: "Embark on our signature 2-hour coastal odyssey. You will gentle-trot through the aromatic eucalyptus forest, trace the outer perimeter of the Moroccan Royal Palace and manicured fairways, before breaking through the rolling sand dunes of the Souss River estuary where migratory pink flamingos congregate in the setting sun.",
    feat_1: "Free Agadir & Taghazout Pickups",
    feat_2: "Eucalyptus & Beach Sand Dunes",
    feat_3: "Flamingo Sanctuary at River Souss",
    feat_4: "Moroccan Mint Tea & Sweet Biscuits",
    no_prepayment: "No prepayment required • Pay on pickup",
    discover_exp: "DISCOVER THE EXPERIENCE",
    package_10_title: "2 Hours Ride",
    package_10_sub: "Sunset Standard",
    package_10_desc: "Full 2-hour guided camel sunset journey without dinner. Ideal for couples, solo travelers, and light afternoon itineraries.",
    select_10: "Select €10 Package",
    package_15_title: "2 Hours + Moroccan Dinner",
    package_15_sub: "Gourmet Sunset & Feast",
    package_15_desc: "Our premier evening. Full 2-hour sunset trek followed by an authentic Moroccan chicken/meat tagine dinner, fresh bread, and seasonal fruits under the Berber tent.",
    select_15: "Select €15 Dinner Package",
    most_popular: "MOST POPULAR",

    // Route Timeline
    timeline_badge: "The 8-Step Itinerary",
    timeline_title: "HOW YOUR SUNSET JOURNEY UNFOLDS",
    timeline_desc: "Every minute is planned so you relax, savor the coastal air, and capture stunning portraits.",

    // Route Timeline — info cards
    route_card_title: "Route",
    route_card_desc: "Trails wind past the royal palace area, eucalyptus woods, and the Souss River estuary where pink flamingos and migratory birds are often visible.",
    duration_card_title: "Duration",
    duration_card_desc: "About 2 hours total, which includes roughly 45 to 60 minutes of actual riding time plus hotel transfers and a welcome break.",
    inclusions_card_title: "Inclusions",
    inclusions_card_desc: "Most standard bookings feature hotel pickup and drop-off in an air-conditioned vehicle, a local guide, the camel trek, and traditional Moroccan mint tea with cookies.",
    inclusions_item_1: "Air-conditioned hotel transfer",
    inclusions_item_2: "Local guide",
    inclusions_item_3: "Camel trek",
    inclusions_item_4: "Moroccan mint tea & cookies",
    safety_card_title: "Safety",
    safety_card_desc: "No prior experience is required. The pace is slow and calm, and local handlers lead the animals by foot the entire way.",
    safety_tag_1: "Beginners welcome",
    safety_tag_2: "Gentle pace",
    safety_tag_3: "Local handlers",
    safety_tag_4: "Family-friendly",

    // What to Wear
    what_to_wear_title: "What to Wear",
    what_to_wear_desc: "Comfortable casual clothing, closed-toe shoes or secure sandals, sunglasses, and a sun hat.",
    what_to_wear_item_1: "Comfortable casual clothing",
    what_to_wear_item_2: "Closed-toe shoes or secure sandals",
    what_to_wear_item_3: "Sunglasses",
    what_to_wear_item_4: "Sun hat",

    // Family Suitability
    family_suit_title: "Family Suitability",
    family_suit_desc: "Great for kids. Toddlers under 3 usually ride with an adult, while children ages 4 to 8 can ride on a led animal next to a handler.",
    family_suit_item_1: "Great for kids of all ages",
    family_suit_item_2: "Toddlers under 3 ride with an adult",
    family_suit_item_3: "Ages 4–8 ride led animal with handler",
    family_suit_item_4: "Safe & supervised at all times",

    pill_duration: "Total Duration: ~2 Hours",
    pill_transfer: "Round-trip Transfer Included",
    pill_photos: "Complimentary Photos",

    // Horse Riding
    horse_badge: "Coastal Equestrian Excursions",
    horse_title: "HORSE RIDING IN AGADIR",
    horse_desc: "Experience the thrill of riding spirited yet calm Arabian-Barb horses through sandy trails, fragrant eucalyptus woods, and open ocean shorelines. Whether you are stepping onto a stirrup for the first time or longing to gallop down Moroccan sands, our equestrian masters tailor every stride.",
    safety_first: "Safety First",
    safety_desc: "Helmets & safety briefing for every guest.",
    purebred: "Purebred Horses",
    purebred_desc: "Well-cared-for, responsive Moroccan steeds.",
    guide_escort: "Guide Escort",
    guide_desc: "Dedicated escort riding alongside you.",
    horse_10: "2 Hours Horse Riding",
    horse_15: "2 Hours + Tagine Dinner",
    book_for_10: "Book for €10",
    book_for_15: "Book for €15",

    // More Adventures
    adv_badge: "Agadir Thrills & Water",
    adv_title: "MORE OUTDOOR ADVENTURES",
    adv_desc: "Combine your camel sunset with quad biking adrenaline, Taghazout surf breaks, or scenic ocean boat excursions.",
    custom_pkg: "Need custom multi-activity packages? Call us",
    discover: "Discover",

    // Day Tours
    tours_badge: "Full & Half-Day Day Trips",
    tours_title: "DISCOVER MOROCCO — TOURS & EXCURSIONS",
    tours_desc: "Step beyond Agadir. Venture to emerald mountain pools, red sandstone sea arches, and ancient walled medinas.",
    reserve_tour: "Reserve Tour →",

    // Gallery & Contact
    gallery_badge: "Real Guests, Real Magic",
    gallery_title: "SUNSET GALLERY PREVIEW",
    insta_follow: "Follow @AgadirCamelExperience",
    instant_confirm: "Instant Confirmation",
    ready_title: "READY FOR YOUR AGADIR ADVENTURE?",
    ready_desc: "Reserve in 2 minutes. No advance payment required — pay comfortably on pickup. Call, WhatsApp, or request pickup right here.",
    book_whatsapp: "BOOK NOW VIA WHATSAPP",
    book_online: "BOOK ONLINE FORM",
    daily_ops: "Daily Operations: 7:00 AM - 9:00 PM",
    call_desk: "Call Desk",
    whatsapp_chat: "WhatsApp Chat",

    // ContactCTA Form
    contact_form_title: "Send Us a Direct Message",
    contact_form_sub: "Fill in your details below to request a pickup or inquire about custom tours.",
    form_full_name: "Full Name *",
    form_name_placeholder: "e.g. John Doe",
    form_email: "Email Address *",
    form_email_placeholder: "john@example.com",
    form_phone: "Phone / WhatsApp",
    form_experience: "Interested Experience",
    form_message: "Your Message / Special Requests *",
    form_message_placeholder: "Let us know your hotel location, preferred date, and number of travelers...",
    form_sending: "SENDING MESSAGE...",
    form_send_btn: "SEND MESSAGE VIA EMAIL",
    form_whatsapp_alt: "Or prefer instant messaging?",
    form_whatsapp_link: "Chat on WhatsApp",
    form_success: "Thank you! Your message has been sent successfully. We will get back to you shortly.",
    form_error: "Failed to send message. Please try calling or WhatsApp directly.",

    // Footer
    footer_tagline: "Discover Agadir. Live the authentic Moroccan experience with desert sunset treks, scenic dunes, and coastal ocean paths.",
    footer_col2_title: "Core Experiences",
    footer_link_camel_sunset: "Camel Sunset Experience",
    footer_link_dinner_trek: "Moroccan Dinner Trek",
    footer_link_horse_beach: "Horse Riding Forest & Beach",
    footer_link_sunrise: "Sunrise Camel Tour",
    footer_col3_title: "Adventures & Excursions",
    footer_link_quad: "Quad & Buggy Safari",
    footer_link_surf: "Surf & Ocean Sports",
    footer_link_paradise: "Paradise Valley Day Trip",
    footer_link_essaouira: "Essaouira Coastal Tour",
    footer_link_marrakech: "Marrakech Heritage Excursion",
    footer_col4_title: "Trust & Assurance",
    footer_trust_1: "Free Hotel Pickup in Agadir & Taghazout",
    footer_trust_2: "Professional Local Guides",
    footer_trust_3: "No Advance Deposit Required",
    footer_trust_4: "100% Authentic Moroccan Hospitality",
    footer_wa_desk: "Direct WhatsApp & Reservation Desk Active",
    footer_copyright: "© 2026 Agadir Camel Experience. All rights reserved. Souss-Massa, Morocco.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_pickup: "Pickup Locations",

    // FeaturedExperience — package bullet lists
    feat_pkg10_b1: "Hotel pickup & drop-off included",
    feat_pkg10_b2: "Moroccan mint tea & fresh pastry pause",
    feat_pkg10_b3: "Professional local guide assistance",
    feat_pkg15_b1: "All 2-hour sunset trek inclusions",
    feat_pkg15_b2: "Fresh clay-pot Berber Tagine dinner",
    feat_pkg15_b3: "Desert campfire & starry sky relaxation",
    per_person: "/ person",
    per_person_all: "/ person (All-Inclusive)",

    // HorseRiding — inline hardcoded texts
    horse_pkg10_label: "Ride Only",
    horse_pkg10_desc: "Includes hotel pickup, helmet, trail guide, and refreshing mint tea.",
    horse_pkg15_label: "Ride & Feast",
    horse_pkg15_desc: "Includes ride, transfers, and a complete evening Moroccan tagine dinner.",
    horse_levels: "All Levels",
    horse_levels_sub: "Beginner to Advanced",
    horse_quote: "\"The bond between rider, dunes, and the Atlantic breeze is pure poetry.\"",
    horse_stables: "Arabian-Barb Stables",

    // MoreAdventures — activity data
    act_quad_title: "Quad Biking Safari",
    act_quad_duration: "2 Hours",
    act_quad_desc: "Conquer the coastal sand dunes and eucalyptus forest tracks with high-performance 250cc ATVs.",
    act_buggy_title: "Buggy Safari",
    act_buggy_duration: "2 Hours",
    act_buggy_desc: "High adrenaline tandem dune buggies, perfect for couples and thrill seekers across Takkat sands.",
    act_surf_title: "Surf & Ocean Waves",
    act_surf_duration: "Half Day",
    act_surf_desc: "Learn to surf in world-renowned Taghazout & Anza swells. Equipment and certified coaching included.",
    act_jetski_title: "Jet Ski Marina Thrill",
    act_jetski_duration: "30 Mins",
    act_jetski_desc: "Skim across the warm calm waters of Agadir bay facing the historic Kasbah mountain.",
    act_boat_title: "Boat Cruise & Fishing",
    act_boat_duration: "Half Day",
    act_boat_desc: "Relax on the open ocean with rod fishing, swimming stops, and fresh grilled fish lunch onboard.",
    act_city_title: "Agadir City Tour",
    act_city_duration: "3 Hours",
    act_city_desc: "Visit the historic Kasbah Oufella, buzzing Souk El Had market, and an authentic Argan oil cooperative.",
    act_berber_title: "Berber Country Tour",
    act_berber_duration: "4 Hours",
    act_berber_desc: "Explore rustic countryside hamlets, traditional honey apiaries, and rural foothill landscapes.",
    act_bike_title: "Bicycle & E-Bike",
    act_bike_duration: "Full Day",
    act_bike_desc: "Cruise Agadir's 10km paved seaside corniche at your leisure with premium city bikes and helmets.",
    act_from: "From",

    // DayTours — tour data
    tour_paradise_title: "Paradise Valley",
    tour_paradise_timing: "8:30 AM – 2:00 PM",
    tour_paradise_desc: "Trek through the Immouzzer foothills, swim in natural turquoise limestone pools, and relax at sunlit riverside cafes.",
    tour_massa_title: "Massa & Tiznit",
    tour_massa_timing: "Full Day Excursion",
    tour_massa_desc: "Explore the Massa National Bird Park, fisherman cave dwellings at Sidi Rbat, and Tiznit's renowned Berber silver medina.",
    tour_tiout_title: "Tiout & Taroudant",
    tour_tiout_timing: "Full Day with Lunch",
    tour_tiout_desc: "\"Little Marrakech\" — witness 6km of intact adobe ramparts, lively Berber craft markets, and the sprawling palm oasis of Tiout.",
    tour_essaouira_title: "Essaouira (Mogador)",
    tour_essaouira_timing: "Full Day Departure",
    tour_essaouira_desc: "UNESCO World Heritage coastal citadel with whitewashed alleyways, blue shutters, artisan thuya wood shops, and fresh seafood.",
    tour_marrakech_title: "Marrakech Day Trip",
    tour_marrakech_timing: "7:00 AM – 8:00 PM",
    tour_marrakech_desc: "The Red City: Visit the majestic Bahia Palace, Koutoubia gardens, the bustling souks of the Medina, and mythical Jemaa el-Fnaa.",
    tour_legzira_title: "Legzira Sea Arches",
    tour_legzira_timing: "Full Day Coastal",
    tour_legzira_desc: "Morocco's most photographed wild ocean beach, known for immense red stone arches sculpted by tides, followed by fresh grilled fish.",
    per_person_short: "/ person",

    // Adventures Dropdown
    opt_camel_10: "Camel Sunset Trek (2h)",
    opt_camel_15: "Camel + Dinner (2h)",
    opt_horse_10: "Horse Riding (2h)",
    opt_horse_15: "Horse Riding + Dinner (2h)",
    price_10_fake: "€18",
    price_10_real: "€10",
    price_15_fake: "€25",
    price_15_real: "€15",
    special_discount: "🔥 Flash Sale: Special discount for this moment",

    // About Us & FAQ
    about_badge: "Get to Know Us",
    about_title: "FREQUENTLY ASKED QUESTIONS",
    about_desc: "Everything you need to know about our tours, bookings, and what to expect on your Moroccan adventure.",
    faq_1_q: "Do I need any prior riding experience?",
    faq_1_a: "Not at all! Our camels and horses are very calm and well-trained. Our professional guides will give you a brief training and walk alongside you the entire time to ensure your safety and comfort.",
    faq_2_q: "What should I wear for the camel or horse ride?",
    faq_2_a: "We recommend comfortable, loose-fitting clothes (like long trousers or leggings) to avoid chafing, and closed-toe shoes. Don't forget a hat and sunglasses for the sun, and a light jacket for sunset rides as it can get chilly.",
    faq_3_q: "Is hotel pick-up and drop-off included in the price?",
    faq_3_a: "Yes! We offer complimentary air-conditioned round-trip transfers from any hotel or accommodation in Agadir and Taghazout.",
    faq_4_q: "How do I pay? Do I need to pay in advance?",
    faq_4_a: "No prepayment or credit card is required to book. You can reserve your spot online or via WhatsApp and pay in cash (Euros, Dirhams, or Dollars) directly to your driver upon pickup.",
    faq_5_q: "Can children participate in these activities?",
    faq_5_a: "Absolutely. Our activities are very family-friendly. Children under a certain age can ride the same camel with an adult. We ensure extra safety measures for our younger guests.",

    // Pricing Plans
    pricing_badge: "Popular Options & Pricing",
    pricing_title: "TRANSPARENT PRICING FOR EVERY ADVENTURE",
    pricing_desc: "No hidden fees. No surprises. Choose the experience that fits your style and budget — pay comfortably on pickup.",
    pricing_per_adult: "/ adult",
    pricing_popular_badge: "MOST POPULAR",

    pricing_standard_sub: "Forest & River Trek",
    pricing_standard_title: "Standard Camel Ride",
    pricing_standard_price: "$12–$17",
    pricing_standard_desc: "Our classic coastal trek through the aromatic eucalyptus forest to the Souss River estuary, paired with traditional Moroccan mint tea and sweet snacks.",
    pricing_standard_f1: "Eucalyptus forest & river trail",
    pricing_standard_f2: "Moroccan mint tea & snacks included",
    pricing_standard_f3: "Hotel pickup & drop-off",
    pricing_standard_btn: "Book Standard Ride",

    pricing_sunset_sub: "Gourmet Sunset Experience",
    pricing_sunset_title: "Sunset Ride + BBQ Dinner",
    pricing_sunset_price: "$17–$29",
    pricing_sunset_desc: "Our premier evening package — a full sunset camel trek followed by an authentic Moroccan barbecue and traditional couscous under the open sky.",
    pricing_sunset_f1: "Full sunset camel trek",
    pricing_sunset_f2: "Moroccan BBQ & couscous dinner",
    pricing_sunset_f3: "Hotel transfers included",
    pricing_sunset_btn: "Book Sunset + Dinner",

    pricing_combo_sub: "Desert & Beach Action",
    pricing_combo_title: "Quad Bike + Camel Combo",
    pricing_combo_price: "$19–$33",
    pricing_combo_desc: "The ultimate Agadir adventure — conquer the coastal dunes on a 250cc quad then switch to a camel for a serene sunset trot along the ocean shoreline.",
    pricing_combo_f1: "Quad biking on coastal dunes",
    pricing_combo_f2: "Camel ride along the shoreline",
    pricing_combo_f3: "Combined discount package",
    pricing_combo_btn: "Book Combo Package",

    pricing_trust_1: "No advance payment required",
    pricing_trust_2: "Pay in cash on pickup (€, $, MAD)",
    pricing_trust_3: "Free hotel pickup included"
  },
  fr: {
    // Header
    nav_home: "ACCUEIL",
    nav_experiences: "EXPÉRIENCES",
    nav_activities: "ACTIVITÉS",
    nav_tours: "EXCURSIONS",
    nav_gallery: "GALERIE",
    nav_pricing: "TARIFS",
    nav_route: "PARCOURS",
    nav_horse_riding: "CHEVAUX",
    nav_about: "À PROPOS",
    nav_contact: "CONTACT",
    book_experience: "RÉSERVER",

    // Hero
    hero_badge: "Aventures Désert & Littoral Marocain",
    hero_title_1: "VIVEZ AGADIR",
    hero_title_2: "DIFFÉREMMENT",
    hero_desc: "Balades authentiques à dos de chameau, couchers de soleil sur l'océan et promenades équestres. Glissez à travers les forêts d'eucalyptus et les dunes pendant l'heure dorée du Maroc.",
    hero_chip_1: "Expériences Chameau",
    hero_chip_2: "Équitation",
    hero_chip_3: "Coucher de soleil Atlantique",
    hero_chip_4: "Tours Vallée du Souss",
    hero_chip_5: "Safaris Désert",
    btn_book: "RÉSERVEZ VOTRE EXPÉRIENCE",
    btn_explore: "EXPLORER LES ACTIVITÉS",

    // Booking Form
    form_adventure: "Choisir l'aventure",
    form_date: "Sélectionner la date",
    form_travelers: "Voyageurs",
    btn_check_availability: "Vérifier la disponibilité",
    person_1: "1 Personne (Privé ou Groupe)",
    person_2: "2 Voyageurs",
    person_3: "3 Voyageurs",
    person_4: "4 Voyageurs",
    person_5: "Groupe Familial (5+)",

    // Why Us
    why_badge: "La différence de confiance Agadir",
    why_title: "POURQUOI LES VOYAGEURS ADORENT AGADIR CAMEL EXPERIENCE",
    why_desc: "Des rencontres désertiques authentiques avec la vraie chaleur berbère, un transport porte-à-porte fiable et sans aucune mauvaise surprise.",
    pillar_1_title: "Expériences Authentiques",
    pillar_1_desc: "Hospitalité berbère authentique, selles traditionnelles en cuir faites à la main et sentiers calmes le long des dunes côtières et de la rivière Souss.",
    pillar_1_tag: "Héritage Berbère",
    pillar_2_title: "Transfert Hôtel Inclus",
    pillar_2_desc: "Transfert gratuit en van climatisé depuis la réception de votre hôtel à Agadir ou Taghazout, retour sécurisé juste après la balade.",
    pillar_2_tag: "Agadir & Taghazout",
    pillar_3_title: "Équipe Locale Chaleureuse",
    pillar_3_desc: "Chameliers locaux expérimentés et multilingues qui vous accueillent comme en famille, prennent des photos et partagent des anecdotes.",
    pillar_3_tag: "Guides Locaux",
    pillar_4_title: "Couchers de Soleil Inoubliables",
    pillar_4_desc: "Des départs soigneusement planifiés pour vous placer devant les dunes atlantiques exactement quand le ciel se teinte d'ambre et d'or.",
    pillar_4_tag: "Heure Dorée",

    // Featured Experience
    iconic_badge: "Le Parcours le Plus Iconique",
    camel_sunset_title: "EXPÉRIENCE CHAMEAU AU COUCHER DU SOLEIL",
    camel_sunset_desc: "Embarquez pour notre odyssée côtière de 2 heures. Vous traverserez doucement la forêt d'eucalyptus parfumée, longez le Palais Royal et les greens du golf, avant d'atteindre les dunes de l'estuaire du Souss où se rassemblent les flamants roses au coucher du soleil.",
    feat_1: "Transfert Gratuit Agadir & Taghazout",
    feat_2: "Forêt d'Eucalyptus & Dunes de Plage",
    feat_3: "Santuaires de Flamants Roses au Souss",
    feat_4: "Thé à la Menthe & Biscuits Marocains",
    no_prepayment: "Aucun prépaiement requis • Payez au ramassage",
    discover_exp: "DÉCOUVRIR L'EXPÉRIENCE",
    package_10_title: "Balade 2 Heures",
    package_10_sub: "Coucher de soleil Standard",
    package_10_desc: "Circuit guidé complet de 2h à dos de chameau sans dîner. Idéal pour les couples, voyageurs solos et itinéraires légers.",
    select_10: "Choisir l'offre €10",
    package_15_title: "2h + Dîner Marocain",
    package_15_sub: "Coucher de soleil & Festin",
    package_15_desc: "Notre soirée vedette. 2 heures de balade suivies d'un dîner  marocain authentique (poulet/viande), pain frais et fruits sous tente berbère.",
    select_15: "Choisir l'offre €15 Dîner",
    most_popular: "LE PLUS POPULAIRE",

    // Route Timeline
    timeline_badge: "Itinéraire en 8 Étapes",
    timeline_title: "DÉROULEMENT DE VOTRE EXPÉRIENCE",
    timeline_desc: "Chaque minute est organisée pour vous détendre, savourer l'air marin et capturer de superbes photos.",

    // Route Timeline — info cards
    route_card_title: "Le Parcours",
    route_card_desc: "Les sentiers serpentent autour du palais royal, traversent les forêts d'eucalyptus et longent l'estuaire du Souss où flamants roses et oiseaux migrateurs sont souvent visibles.",
    duration_card_title: "Durée",
    duration_card_desc: "Environ 2 heures au total, dont 45 à 60 minutes de randonnée effective, plus les transferts hôteliers et une pause de bienvenue.",
    inclusions_card_title: "Inclus",
    inclusions_card_desc: "La plupart des réservations standard comprennent le transfert hôtel aller-retour en véhicule climatisé, un guide local, la balade à dos de chameau, et le thé à la menthe marocain avec des gâteaux.",
    inclusions_item_1: "Transfert hôtel climatisé",
    inclusions_item_2: "Guide local",
    inclusions_item_3: "Balade à dos de chameau",
    inclusions_item_4: "Thé à la menthe & gâteaux",
    safety_card_title: "Sécurité",
    safety_card_desc: "Aucune expérience préalable n'est requise. L'allure est lente et calme, et des accompagnateurs locaux guident les animaux à pied tout au long du parcours.",
    safety_tag_1: "Débutants bienvenus",
    safety_tag_2: "Rythme doux",
    safety_tag_3: "Encadreurs locaux",
    safety_tag_4: "Adapté aux familles",

    // What to Wear
    what_to_wear_title: "Tenue Recommandée",
    what_to_wear_desc: "Vêtements décontractés et confortables, chaussures fermées ou sandales stables, lunettes de soleil et chapeau.",
    what_to_wear_item_1: "Vêtements décontractés et confortables",
    what_to_wear_item_2: "Chaussures fermées ou sandales stables",
    what_to_wear_item_3: "Lunettes de soleil",
    what_to_wear_item_4: "Chapeau de soleil",

    // Family Suitability
    family_suit_title: "Adapté aux Familles",
    family_suit_desc: "Idéal pour les enfants. Les tout-petits de moins de 3 ans montent généralement avec un adulte, et les enfants de 4 à 8 ans peuvent monter sur un animal guidé avec un accompagnateur.",
    family_suit_item_1: "Idéal pour les enfants de tout âge",
    family_suit_item_2: "Moins de 3 ans : monter avec un adulte",
    family_suit_item_3: "4–8 ans : animal guidé avec accompagnateur",
    family_suit_item_4: "Sécurisé et encadré à tout moment",

    pill_duration: "Durée totale : ~2 heures",
    pill_transfer: "Transfert aller-retour inclus",
    pill_photos: "Photos offertes",

    // Horse Riding
    horse_badge: "Excursions Équestres Côtières",
    horse_title: "ÉQUITATION À AGADIR",
    horse_desc: "Ressentez la sensation de monter des chevaux barbe-arabes énergiques mais dociles à travers les dunes, la forêt d'eucalyptus et la plage. Que ce soit votre première fois ou que vous souhaitiez galoper sur les sables marocains, nos moniteurs adaptent la balade.",
    safety_first: "Sécurité Avant Tout",
    safety_desc: "Casques et briefing de sécurité pour tous.",
    purebred: "Chevaux de Race",
    purebred_desc: "Chevaux marocains bien soignés et attentifs.",
    guide_escort: "Accompagnement Guide",
    guide_desc: "Un guide dédié chevauche à vos côtés.",
    horse_10: "2 Heures Équitation",
    horse_15: "2 Heures + Dîner ",
    book_for_10: "Réserver pour €10",
    book_for_15: "Réserver pour €15",

    // More Adventures
    adv_badge: "Sensations & Ocean Agadir",
    adv_title: "PLUS D'AVENTURES EN PLEIN AIR",
    adv_desc: "Combinez votre coucher de soleil à chameau avec le quad dans les dunes, le surf à Taghazout ou une balade en bateau.",
    custom_pkg: "Besoin d'un package multi-activités personnalisé ? Appelez-nous",
    discover: "Découvrir",

    // Day Tours
    tours_badge: "Excursions d'une Journée ou Demi-Journée",
    tours_title: "DÉCOUVREZ LE MAROC — TOURS & EXCURSIONS",
    tours_desc: "Allez au-delà d'Agadir. Explorez les piscines naturelles de montagne, les arches de grès rouge et les médinas historiques.",
    reserve_tour: "Réserver Excursion →",

    // Gallery & Contact
    gallery_badge: "Vrais Clients, Vraie Magie",
    gallery_title: "APERÇU DE LA GALERIE",
    insta_follow: "Suivre @AgadirCamelExperience",
    instant_confirm: "Confirmation Immédiate",
    ready_title: "PRÊT POUR VOTRE AVENTURE À AGADIR ?",
    ready_desc: "Réservez en 2 minutes. Aucun paiement d'avance requis — payez directement au ramassage. Appelez ou envoyez un message WhatsApp.",
    book_whatsapp: "RÉSERVER VIA WHATSAPP",
    book_online: "FORMULAIRE EN LIGNE",
    daily_ops: "Service client : 7h00 - 21h00",
    call_desk: "Appeler",
    whatsapp_chat: "Chat WhatsApp",

    // ContactCTA Form
    contact_form_title: "Envoyez-nous un Message Direct",
    contact_form_sub: "Remplissez vos coordonnées pour demander un ramassage ou renseignez-vous sur des circuits personnalisés.",
    form_full_name: "Nom Complet *",
    form_name_placeholder: "ex. Jean Dupont",
    form_email: "Adresse Email *",
    form_email_placeholder: "jean@exemple.com",
    form_phone: "Téléphone / WhatsApp",
    form_experience: "Expérience Souhaitée",
    form_message: "Votre Message / Demandes Spéciales *",
    form_message_placeholder: "Indiquez votre hôtel, la date souhaitée et le nombre de voyageurs...",
    form_sending: "ENVOI EN COURS...",
    form_send_btn: "ENVOYER LE MESSAGE PAR EMAIL",
    form_whatsapp_alt: "Vous préférez la messagerie instantanée ?",
    form_whatsapp_link: "Chat sur WhatsApp",
    form_success: "Merci ! Votre message a été envoyé avec succès. Nous vous répondrons très prochainement.",
    form_error: "Échec de l'envoi. Veuillez appeler ou écrire directement sur WhatsApp.",

    // Footer
    footer_tagline: "Découvrez Agadir. Vivez l'expérience marocaine authentique avec des treks au coucher du soleil, des dunes pittoresques et des sentiers côtiers.",
    footer_col2_title: "Expériences Phares",
    footer_link_camel_sunset: "Expérience Chameau Coucher de Soleil",
    footer_link_dinner_trek: "Trek Dîner Marocain",
    footer_link_horse_beach: "Équitation Forêt & Plage",
    footer_link_sunrise: "Balade Chameau Lever de Soleil",
    footer_col3_title: "Aventures & Excursions",
    footer_link_quad: "Safari Quad & Buggy",
    footer_link_surf: "Surf & Sports Nautiques",
    footer_link_paradise: "Excursion Vallée du Paradis",
    footer_link_essaouira: "Circuit Côtier Essaouira",
    footer_link_marrakech: "Excursion Patrimoine Marrakech",
    footer_col4_title: "Confiance & Garanties",
    footer_trust_1: "Transfert Hôtel Gratuit Agadir & Taghazout",
    footer_trust_2: "Guides Locaux Professionnels",
    footer_trust_3: "Aucun Acompte Requis",
    footer_trust_4: "100% Hospitalité Marocaine Authentique",
    footer_wa_desk: "WhatsApp Direct & Bureau de Réservation Actif",
    footer_copyright: "© 2025 Agadir Camel Experience. Tous droits réservés. Souss-Massa, Maroc.",
    footer_privacy: "Politique de Confidentialité",
    footer_terms: "Conditions d'Utilisation",
    footer_pickup: "Points de Ramassage",

    // FeaturedExperience — package bullet lists
    feat_pkg10_b1: "Transfert hôtel aller-retour inclus",
    feat_pkg10_b2: "Thé à la menthe marocain & pause pâtisserie",
    feat_pkg10_b3: "Assistance guide local professionnel",
    feat_pkg15_b1: "Toutes les prestations du trek 2h coucher de soleil",
    feat_pkg15_b2: "Tajine berbère frais en poterie",
    feat_pkg15_b3: "Feu de camp & relaxation sous les étoiles",
    per_person: "/ personne",
    per_person_all: "/ personne (Tout Inclus)",

    // HorseRiding — inline hardcoded texts
    horse_pkg10_label: "Balade Seule",
    horse_pkg10_desc: "Inclut le transfert hôtel, casque, guide de piste et thé à la menthe rafraîchissant.",
    horse_pkg15_label: "Balade & Festin",
    horse_pkg15_desc: "Inclut la balade, les transferts et un dîner complet à base de tajine marocain.",
    horse_levels: "Tous Niveaux",
    horse_levels_sub: "Débutant à Confirmé",
    horse_quote: "\"Le lien entre le cavalier, les dunes et la brise atlantique est pure poésie.\"",
    horse_stables: "Écuries Barbe-Arabe",

    // MoreAdventures — activity data
    act_quad_title: "Safari Quad",
    act_quad_duration: "2 Heures",
    act_quad_desc: "Dominez les dunes côtières et les pistes en forêt d'eucalyptus avec des quads 250cc haute performance.",
    act_buggy_title: "Safari Buggy",
    act_buggy_duration: "2 Heures",
    act_buggy_desc: "Buggies tandem à haute adrénaline, parfaits pour les couples et amateurs de sensations sur les sables de Takkat.",
    act_surf_title: "Surf & Vagues Océan",
    act_surf_duration: "Demi-Journée",
    act_surf_desc: "Apprenez le surf dans les vagues réputées de Taghazout & Anza. Équipement et coaching certifié inclus.",
    act_jetski_title: "Jet Ski Marina",
    act_jetski_duration: "30 Min",
    act_jetski_desc: "Glissez sur les eaux calmes de la baie d'Agadir face à la montagne historique de la Kasbah.",
    act_boat_title: "Croisière & Pêche",
    act_boat_duration: "Demi-Journée",
    act_boat_desc: "Détendez-vous en mer avec la pêche à la ligne, des arrêts baignade et un déjeuner de poisson grillé frais.",
    act_city_title: "Tour d'Agadir",
    act_city_duration: "3 Heures",
    act_city_desc: "Visitez la Kasbah Oufella historique, le marché Souk El Had et une coopérative d'huile d'argan authentique.",
    act_berber_title: "Tour Campagne Berbère",
    act_berber_duration: "4 Heures",
    act_berber_desc: "Explorez les hameaux rustiques, les apiculteurs traditionnels et les paysages de piémont rural.",
    act_bike_title: "Vélo & Vélo Électrique",
    act_bike_duration: "Journée Complète",
    act_bike_desc: "Parcourez les 10 km de la corniche pavée d'Agadir à votre rythme avec des vélos premium et casques.",
    act_from: "À partir de",

    // DayTours — tour data
    tour_paradise_title: "Vallée du Paradis",
    tour_paradise_timing: "8h30 – 14h00",
    tour_paradise_desc: "Trek dans les contreforts d'Immouzzer, baignade dans des piscines naturelles turquoise et détente dans des cafés au bord de la rivière.",
    tour_massa_title: "Massa & Tiznit",
    tour_massa_timing: "Excursion Journée Complète",
    tour_massa_desc: "Explorez le Parc National des Oiseaux de Massa, les grottes de pêcheurs à Sidi Rbat et la médina de l'argent berbère de Tiznit.",
    tour_tiout_title: "Tiout & Taroudant",
    tour_tiout_timing: "Journée Complète avec Déjeuner",
    tour_tiout_desc: "\"Petite Marrakech\" — admirez 6 km de remparts en adobe intacts, des marchés d'artisanat berbère et l'immense oasis de palmiers de Tiout.",
    tour_essaouira_title: "Essaouira (Mogador)",
    tour_essaouira_timing: "Départ Journée Complète",
    tour_essaouira_desc: "Cité côtière classée au Patrimoine Mondial de l'UNESCO avec ruelles blanchies, volets bleus, boutiques de thuya et fruits de mer frais.",
    tour_marrakech_title: "Excursion Marrakech",
    tour_marrakech_timing: "7h00 – 20h00",
    tour_marrakech_desc: "La Ville Rouge : Palais de la Bahia, jardins Koutoubia, souks animés de la Médina et mythique Jemaa el-Fnaa.",
    tour_legzira_title: "Arches de Legzira",
    tour_legzira_timing: "Journée Côtière Complète",
    tour_legzira_desc: "La plage sauvage la plus photographiée du Maroc, célèbre pour ses immenses arches de grès rouge sculptées par les marées et un délicieux poisson grillé.",
    per_person_short: "/ pers.",

    // Adventures Dropdown
    opt_camel_10: "Balade Chameau (2h)",
    opt_camel_15: "Chameau + Dîner (2h)",
    opt_horse_10: "Équitation (2h)",
    opt_horse_15: "Équitation + Dîner (2h)",
    price_10_fake: "€18",
    price_10_real: "€10",
    price_15_fake: "€25",
    price_15_real: "€15",
    special_discount: "🔥 Vente Flash : Remise spéciale en ce moment",

    // About Us & FAQ
    about_badge: "Faisons Connaissance",
    about_title: "FOIRE AUX QUESTIONS",
    about_desc: "Tout ce que vous devez savoir sur nos excursions, les réservations et ce qui vous attend lors de votre aventure marocaine.",
    faq_1_q: "Ai-je besoin d'une expérience préalable en équitation ?",
    faq_1_a: "Pas du tout ! Nos chameaux et chevaux sont très calmes et bien entraînés. Nos guides vous donneront une brève formation et marcheront à vos côtés pendant tout le trajet pour assurer votre sécurité.",
    faq_2_q: "Que dois-je porter pour la balade à chameau ou à cheval ?",
    faq_2_a: "Nous recommandons des vêtements confortables et amples (pantalons longs ou leggings) pour éviter les frottements, et des chaussures fermées. N'oubliez pas un chapeau, des lunettes de soleil et une veste légère pour le soir.",
    faq_3_q: "Le transfert aller-retour à l'hôtel est-il inclus ?",
    faq_3_a: "Oui ! Nous offrons des transferts gratuits aller-retour en véhicule climatisé depuis n'importe quel hôtel ou hébergement à Agadir et Taghazout.",
    faq_4_q: "Comment puis-je payer ? Dois-je payer à l'avance ?",
    faq_4_a: "Aucun prépaiement n'est requis. Vous pouvez réserver votre place en ligne ou par WhatsApp et payer en espèces (Euros, Dirhams ou Dollars) directement à votre chauffeur lors du ramassage.",
    faq_5_q: "Les enfants peuvent-ils participer à ces activités ?",
    faq_5_a: "Absolument. Nos activités sont parfaites pour les familles. Les jeunes enfants peuvent monter sur le même chameau qu'un adulte, et nous prenons des mesures de sécurité supplémentaires pour eux.",

    // Pricing Plans
    pricing_badge: "Options Populaires & Tarifs",
    pricing_title: "TARIFS TRANSPARENTS POUR CHAQUE AVENTURE",
    pricing_desc: "Aucun frais caché. Aucune surprise. Choisissez l'expérience qui correspond à votre style et votre budget — payez confortablement lors du ramassage.",
    pricing_per_adult: "/ adulte",
    pricing_popular_badge: "LE PLUS POPULAIRE",

    pricing_standard_sub: "Trek Forêt & Rivière",
    pricing_standard_title: "Balade Chameau Standard",
    pricing_standard_price: "12–17$",
    pricing_standard_desc: "Notre trek côtier classique à travers la forêt d'eucalyptus jusqu'à l'estuaire du Souss, accompagné d'un thé à la menthe marocain et de sucreries traditionnelles.",
    pricing_standard_f1: "Forêt d'eucalyptus & sentier de la rivière",
    pricing_standard_f2: "Thé à la menthe & snacks inclus",
    pricing_standard_f3: "Transfert hôtel aller-retour",
    pricing_standard_btn: "Réserver la Balade Standard",

    pricing_sunset_sub: "Expérience Coucher de Soleil Gourmet",
    pricing_sunset_title: "Coucher de Soleil + Dîner BBQ",
    pricing_sunset_price: "17–29$",
    pricing_sunset_desc: "Notre formule soirée phare — un trek chameau complet au coucher du soleil suivi d'un barbecue marocain authentique et d'un couscous traditionnel sous le ciel étoilé.",
    pricing_sunset_f1: "Trek chameau au coucher du soleil",
    pricing_sunset_f2: "BBQ marocain & couscous",
    pricing_sunset_f3: "Transferts hôtel inclus",
    pricing_sunset_btn: "Réserver Coucher de Soleil + Dîner",

    pricing_combo_sub: "Désert & Plage",
    pricing_combo_title: "Combo Quad + Chameau",
    pricing_combo_price: "19–33$",
    pricing_combo_desc: "L'aventure ultime à Agadir — dominez les dunes côtières sur un quad 250cc puis passez au chameau pour une tranquille balade au coucher du soleil le long du rivage.",
    pricing_combo_f1: "Quad sur les dunes côtières",
    pricing_combo_f2: "Balade chameau au bord de l'océan",
    pricing_combo_f3: "Tarif réduit package combiné",
    pricing_combo_btn: "Réserver le Package Combo",

    pricing_trust_1: "Aucun paiement d'avance requis",
    pricing_trust_2: "Paiement en espèces au ramassage (€, $, MAD)",
    pricing_trust_3: "Transfert hôtel gratuit inclus"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'en' ? 'fr' : 'en'));
  };

  const t = (key) => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
